# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Yik_cpp_arma <- function(x, t, k) {
    .Call('MultSurvTests_Yik_cpp_arma', PACKAGE = 'MultSurvTests', x, t, k)
}

summandG_cpp_arma <- function(x, y, n, t, t_delta, k) {
    .Call('MultSurvTests_summandG_cpp_arma', PACKAGE = 'MultSurvTests', x, y, n, t, t_delta, k)
}

summandL_cpp_arma <- function(x, y, n, t, t_delta, k) {
    .Call('MultSurvTests_summandL_cpp_arma', PACKAGE = 'MultSurvTests', x, y, n, t, t_delta, k)
}

GehanTest_cpp_arma <- function(x, y, n1, n2, delta_x, delta_y, k) {
    .Call('MultSurvTests_GehanTest_cpp_arma', PACKAGE = 'MultSurvTests', x, y, n1, n2, delta_x, delta_y, k)
}

mvlogrankTest_cpp_arma <- function(x, y, n1, n2, delta_x, delta_y, k) {
    .Call('MultSurvTests_mvlogrankTest_cpp_arma', PACKAGE = 'MultSurvTests', x, y, n1, n2, delta_x, delta_y, k)
}

muG_cpp_arma <- function(x, y, t, k, n = 0L) {
    .Call('MultSurvTests_muG_cpp_arma', PACKAGE = 'MultSurvTests', x, y, t, k, n)
}

muL_cpp_arma <- function(x, y, t, k) {
    .Call('MultSurvTests_muL_cpp_arma', PACKAGE = 'MultSurvTests', x, y, t, k)
}

psiG_cpp_arma <- function(x, y, t, delta_x, k, n) {
    .Call('MultSurvTests_psiG_cpp_arma', PACKAGE = 'MultSurvTests', x, y, t, delta_x, k, n)
}

psiL_cpp_arma <- function(x, y, t, delta_x, k) {
    .Call('MultSurvTests_psiL_cpp_arma', PACKAGE = 'MultSurvTests', x, y, t, delta_x, k)
}

sigma_iklG_cpp_arma <- function(x, y, delta_x, delta_y, k, l, n) {
    .Call('MultSurvTests_sigma_iklG_cpp_arma', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, k, l, n)
}

sigma_iklL_cpp_arma <- function(x, y, delta_x, delta_y, k, l) {
    .Call('MultSurvTests_sigma_iklL_cpp_arma', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, k, l)
}

sigma_klG_cpp_arma <- function(x, y, delta_x, delta_y, k, l, n1, n2) {
    .Call('MultSurvTests_sigma_klG_cpp_arma', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, k, l, n1, n2)
}

sigma_klL_cpp_arma <- function(x, y, delta_x, delta_y, k, l, n1, n2) {
    .Call('MultSurvTests_sigma_klL_cpp_arma', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, k, l, n1, n2)
}

sigma_G_cpp_arma <- function(x, y, delta_x, delta_y, k, l, n1, n2, p) {
    .Call('MultSurvTests_sigma_G_cpp_arma', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, k, l, n1, n2, p)
}

sigma_L_cpp_arma <- function(x, y, delta_x, delta_y, k, l, n1, n2, p) {
    .Call('MultSurvTests_sigma_L_cpp_arma', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, k, l, n1, n2, p)
}

gehan <- function(x, y, delta_x, delta_y, n1, n2, p, k = 1L, l = 1L) {
    .Call('MultSurvTests_gehan', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, n1, n2, p, k, l)
}

mvlogrank <- function(x, y, delta_x, delta_y, n1, n2, p, k = 1L, l = 1L) {
    .Call('MultSurvTests_mvlogrank', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, n1, n2, p, k, l)
}

rcpparma_hello_world <- function() {
    .Call('MultSurvTests_rcpparma_hello_world', PACKAGE = 'MultSurvTests')
}

rcpparma_outerproduct <- function(x) {
    .Call('MultSurvTests_rcpparma_outerproduct', PACKAGE = 'MultSurvTests', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('MultSurvTests_rcpparma_innerproduct', PACKAGE = 'MultSurvTests', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('MultSurvTests_rcpparma_bothproducts', PACKAGE = 'MultSurvTests', x)
}

