# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gehan <- function(x, y, delta_x, delta_y, n1, n2, p, k = 1L, l = 1L) {
    .Call('MultSurvTests_gehan', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, n1, n2, p, k, l)
}

mvlogrank <- function(x, y, delta_x, delta_y, n1, n2, p, k = 1L, l = 1L) {
    .Call('MultSurvTests_mvlogrank', PACKAGE = 'MultSurvTests', x, y, delta_x, delta_y, n1, n2, p, k, l)
}

